name: my-first-drupal9-app
recipe: drupal9
config:
  php: '7.4'
  composer_version: '2.1.6'
  via: apache
  webroot: .
  database: mariadb:10.5
  drush: false
  xdebug: false
services:
  appserver:
    build:
      - composer install
